image:
  repository: hyperledger/burrow
  tag: 0.30.3
  pullPolicy: IfNotPresent

chain:
  logLevel: info
  extraSeeds: []
  testing: false
  restore:
    enabled: false
    dumpURL: ""

config:
  BurrowDir: ".burrow"
  Tendermint:
    Seeds: ""
    SeedMode: false
    ListenHost: "0.0.0.0"
    ListenPort: "26656"
    ExternalAddress: ""
    Moniker: ""
  Keys:
    GRPCServiceEnabled: true
    AllowBadFilePermissions: true
    RemoteAddress: ""
    KeysDirectory: "/keys"
  RPC:
    Info:
      Enabled: true
      ListenHost: "0.0.0.0"
      ListenPort: "26658"
    Profiler:
      Enabled: false
      ListenHost: "0.0.0.0"
      ListenPort: "6060"
    GRPC:
      Enabled: true
      ListenHost: "0.0.0.0"
      ListenPort: "10997"
    Metrics:
      Enabled: true
      ListenHost: "0.0.0.0"
      ListenPort: "9102"
      MetricsPath: "/metrics"
      BlockSampleSize: 100
    Web3:
      Enabled: true
      ListenHost: "0.0.0.0"
      ListenPort: "26660"
  Logging:
    ExcludeTrace: true
    NonBlocking: true
    RootSink:
      Output:
        OutputType: "stderr"
        Format: "json"

validators:
- name: Validator_0
  address: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  nodeAddress: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

contracts:
  # wait required to ensure chain readiness
  enabled: false
  image: ""
  tag: ""
  deploy: ""

extraArgs: {}
environment:
  inline: {}
  secrets: []

organization: "user"

persistence:
  enabled: true
  size: 10Gi
  storageClass: 
  accessMode: ReadWriteOnce
  persistentVolumeReclaimPolicy: "Delete"

peer:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts: []

grpc:
  service:
    type: ClusterIP
    loadBalance: true
  ingress:
    enabled: false
    hosts: []
    annotations: {}
    tls: {}
web3:
  service:
    type: ClusterIP
    loadBalance: true
  ingress:
    enabled: false
    hosts: []
    annotations: {}
    tls: {}

info:
  service:
    type: ClusterIP
    loadBalance: true
  ingress:
    enabled: false
    # exposing partial ingress only exposes
    # the /accounts and /blocks paths outside the cluster
    partial: false
    pathLeader: "/"
    annotations: {}
    hosts: []
    tls: {}

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  enabled: true
  path: /status?block_seen_time_within=10m
  initialDelaySeconds: 240
  timeoutSeconds: 1
  periodSeconds: 30

readinessProbe:
  enabled: true
  path: /status
  initialDelaySeconds: 5

podAnnotations: {}
podLabels: {}

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: 
  nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: blockchain
            operator: In
            values:
              - dev		

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}
validators:
  - name: Validator_0
    address: 4E416FD3D6874846D510B82A040FB2AA69CE8C76
    nodeAddress: 16F35E3973AE346D8386E0937800D3EF08187D78
  - name: Validator_1
    address: CD4B8C444575A3187CF83204EDB0701BB2B0E99F
    nodeAddress: 5CD119CD0FC4868D364916EA1CF46CEF7B4C0057
  - name: Validator_2
    address: 8D84F5623011B5B3FE2D043F1D235390CC0B9366
    nodeAddress: 1720D6FAE77743F49BCDF5FB0E9512FD35721990
  - name: Validator_3
    address: 39824014F410F90CAFE17BFA0F3D0EF80C970A7F
    nodeAddress: 2804949941BEE390088F69BAA249984816C55D6F
  - name: Validator_4
    address: 117ED9201EB79E3F38EF674A7190C89308F0240E
    nodeAddress: 85DC8911FC10758AF1D26DC236E24390C5846D52
